package:
  name: limix_util
  version: 0.1.28

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - h5py
    - humanfriendly
    - matplotlib
    - numba
    - setuptools
    - progressbar
    - cython

about:
  home: http://www.ebi.ac.uk
  license: Private
